### ISSUE TITLE
how to i remove /etc/mtab?

### ISSUE THREAD

**Issue by antsuke42** [fsquillace/junest#107]
the xfe filemanager pops a lot of /optorsomething/something/something mountpoint not responsing.
and i cant get it work. less /etc/mtab in proot says that the file has lotsa of text.
file /etc/mtab in chroot says its symlink to /proc/something/mounts.
file .junest/etc/mtab outside chroot says its empty.
rm /etc/mtab on chroot says it cant.
removing the file ouside chroot has no effect.
and removing on fakeroot has no effect (it appears again)
how to i get rid of it?!

**Comment by fsquillace** [comment]
Hi,
The mtab file is crucial for JuNest and some package you install inside of it.
In fakeroot mode the mtab is mounted --bind automatically from proot and in normal mode the file mtab is generated every time you try to access to junest session.
In order to get more context can you print the output you are seeing and the commands you are typing?

**Comment by fsquillace** [comment]
Resolving in favor of: https://github.com/fsquillace/junest/issues/127
