### ISSUE TITLE
Using with ARM64 architecture?

### ISSUE THREAD

**Issue by CrazyJ36** [fsquillace/junest#110]
Run junest gives "Unknown Architecture" using an ARM64 Samsung Galaxy S6 Edge.
I understand that the use of A mobile phone might not be the best environment or not supported.
I'm using A minimal small "not-so-linux" distrobution app called Termux on Android in this case for testing enhancement to A local terminal.

I think that working with an arm variant would normally just work.
I entered the command under "Using Junest with other architectures" with no success. That section was not very descriptive.
I will keep trying to figure it out myself and maybe answer my own question.

**Comment by fsquillace** [comment]
JuNest should work on arm for 32 bit at the moment. Unfortunately, I did not generate the image for ARM64 since I do not have time :/

I hope I am going to work on this for the next month.
Thanks for spotting this!

**Comment by fsquillace** [comment]
The "Unknow Architecture" is due to the fact that uname commad might provide an unknown architecture name (see also the list of minimal dependencies https://github.com/fsquillace/junest#dependencies).

What do you get from `uname -m` command?

**Comment by CrazyJ36** [comment]
Sorry I lost track of this.

~uname -m
aarch64

I saw A more recent Issue with Android as well. Thanks for your support!

**Comment by fsquillace** [comment]
The check for the architecture is done here: https://github.com/fsquillace/junest/blob/master/lib/core.sh#L65

You might try to change this line of code slightly in order to get the variable ARCH setup as "arm".

Out of curiosity: I am adding more support for JuNest on Android and I need to develop a tutorial (and hopefully in the future an apk) which explain how to use it. Which terminal/android app did you use in order to run the JuNest script?

**Comment by CrazyJ36** [comment]
I used Termux. It's minimal with linux packages actually being ported to Android. https://play.google.com/store/apps/details?id=com.termux

https://github.com/termux

This one has become almost standard for Android. It runs built-in Android commands (whose binaries are in "/system/bin", /system/xbin") with no additions from itself, in case you need A universal way of starting junest. 
https://play.google.com/store/apps/details?id=jackpal.androidterm

https://github.com/jackpal/Android-Terminal-Emulator/wiki

Also for actual Linux distro installs the two Apps  I find most updated are GNURoot Debian and LibuxDeploy.

**Comment by fsquillace** [comment]
For the moment the support for ARM64 cannot be done since the Scaleway service support only ARM 32 bit. Regarding JuNest on Android follow the issue: https://github.com/fsquillace/junest/issues/119

Also, please [join the group](https://groups.google.com/forum/#!forum/junest) if you want to discuss the way the proof of concept should be done. You help will be valuable. :)

Resolving.
