### ISSUE TITLE
Evaluate alternatives to yaourt

### ISSUE THREAD

**Issue by fsquillace** [fsquillace/junest#145]
https://wiki.archlinux.org/index.php/AUR_helpers#Comparison_table

**Comment by fsquillace** [comment]
`cower` can be a possible solution as it is really small program.

`pacaur` is also interesting but it is as complex as `yaourt` and it depends by many command (like `git`, and `sudo`), which make the program heavier than `yaourt`

**Comment by yinflying** [comment]
There is a dirty way to run yaourt with root:

Ref:   [https://github.com/archlinuxfr/yaourt/issues/67](https://github.com/archlinuxfr/yaourt/issues/67)
Dirty solution for the makepkg asroot problem

Background: The maintainers of the makepkg utility used to create Arch packages have, in all their infinite wisdom to protect the lesser beings, removed the asroot option and the possibility to build packages as user root.

My take: Arch started out great because it worked like Slackware: KISS and the ability to shoot yourself in the foot.
Temporary, somewhat ugly fix

We can edit /usr/bin/makepkg of course :-)

Add asroot to OPT_LONG (line 3366). Just search for "OPT_LONG".

OPT_LONG=('allsource' 'check' 'clean' 'cleanbuild' 'config:' 'force' 'geninteg'
          'help' 'holdver' 'ignorearch' 'install' 'key:' 'log' 'noarchive' 'nobuild'
          'nocolor' 'nocheck' 'nodeps' 'noextract' 'noprepare' 'nosign' 'pkg:' 'repackage'
          'rmdeps' 'sign' 'skipchecksums' 'skipinteg' 'skippgpcheck' 'source' 'syncdeps'
          'verifysource' 'version' 'asroot')

Remove EUID check (line 3577). Just search for "EUID".

if (( ! INFAKEROOT )); then
    if (( EUID == 0 )); then
        #error "$(gettext "Running %s as root is not allowed as it can cause permanent,\n\
#catastrophic damage to your system.")" "makepkg"
        #exit 1 # $E_USER_ABORT
        plain "$(gettext "Running as root restored by Orc ;)")"
    fi

Make it permanent

Maybe don't do that. You could consider creating a patch file and applying the patch before running tools such as yaourt, packer or apacman. But soon enough those tools will very likely install a user on your system and let that user run makepkg.

**Comment by fsquillace** [comment]
Thanks @yinflying 
This is not far from what `yogurt` (the yaourt wrapper) does.
The main purpose for this issue is that I wanted to introduce somehow a simpler solution than the heavy `yaourt`, in particular because, according to the [comparison table](https://wiki.archlinux.org/index.php/AUR_helpers#Comparison_table) yaourt does not look to be in a good position :)

`cower` seems quite interesting solution but the benefits of having `yogurt` is because it allows to easily install all corresponding package dependencies.

**Comment by UnicodeAlt255** [comment]
Yeah yaourt is like the matlab of the arch linux community, so many people still use it despite it being possibly one of the worst aur helpers out there.

**Comment by fsquillace** [comment]
Nice analogy :)
In any case `yogurt` has been deprecated as it was not so reliable. To build package you can use the modified version of `makepkg` in `/opt/makepkg/bin/makepkg`. Closing for now.
