### ISSUE TITLE
Non-Sudo package manager

### ISSUE THREAD

**Issue by dhiraj113** [fsquillace/junest#156]
This question could be rather silly. But, anyway I ask.

I want to use Junest to install applications in a Debian/Redhat linux system without sudo permissions. Can Junest be used for this purpose? It looks likely from what have read from StackOverflow and the Readme of this repository, but it hasn't explicitly been specified.

The approach I intend to take is this
1. Install Junest.
2. Use it as a package manager to install Arch Linux packages or applications from source. (with the dependencies managed by Junest)
3. Use the binary as is in the host Debian/Redhat system.

Thanks for your help.

**Comment by fsquillace** [comment]
Hi,

That's true, it is not reported somewhere but IMO there is no such a thing like the sudo permissions concept. sudo is a command that allows to execute command as another user, that's it. This is not strictly the purpose for JuNest. JuNest allow you to run commands in an environment and install packages without being root since it "fakes" the root user but, indeed, the user will always be you. All your packages you are going to install will be placed in the JuNest environment (~/.junest by default).

The three points you mentioned are still valid and represents what basically you can do via JuNest.
