### ISSUE TITLE
I broken by system because of junest

### ISSUE THREAD

**Issue by franko** [fsquillace/junest#167]
Hello,

just to let you know that I broken my system because of junest. It seems that the directory ~/.junest is a link to the / directory or something like that. Trying to remove it I broke my installation and yet I don't know how to get rid of this ".junest" directory.

By the way I was deleting junest out of frustration: in your documentation you *never* explain how the software work and what it does. There are only some bla bla about how to create images and no explication whatsoever about what you should do with the image and how you actually use the software.

**Comment by fsquillace** [comment]
Hey @franko 

The documentation about what JuNest does is just at the top of the README file. Obviously, this image is strongly intended by people that know pretty well how Arch Linux works. So, I suggest to start from it.

Similarly to your requirement about a better documentation, I also need more information about your issue in order to troubleshoot it as it sounds more as a blame without a good cause. This is the [reporting bugs](https://github.com/fsquillace/junest/blob/master/CONTRIBUTING.md#reporting-bugs) section. Please use it if you want be of help.

Thanks

**Comment by franko** [comment]
Hi Filippo,

so actually I didn't break my system and I was able to remove ".junest" from my home directory (even if don't completely understood what was wrong). I admit that when I wrote the issue I was angry and frustrated.

Otherwise I think you should take seriously my words: **in your documentation you don't really explain how to use junest and what it does**. I did read the README several times and I was frustrated to not found this basic information.

To compare I just started using docker the same day and I had no problem by using their documentation.

In any case please feel free to close the issue if you believe there isn't any problem.

**Comment by gmcclins** [comment]
> even if don't completely understood what was wrong

The issue was ```~/.junest/etc/ca-certificates``` contains files/directories with read only permissions. This prevented the removal of ~/.junest directory.
