### ISSUE TITLE
junest run much slower than local machine

### ISSUE THREAD

**Issue by yinflying** [fsquillace/junest#193]
I just find that junest run much slower than local machine,  When I run vim (with many plugins), I find it will run very slow( at least much slower than without junest). Besides, I found that some program seems to run slower with junest.

Is there any way to solve the problem?

**Comment by fsquillace** [comment]
This is due to some limitation from proot: https://github.com/proot-me/PRoot/issues/106

It is possible that junest is attempting to run proot with `PROOT_NO_SECCOMP=1` variable because of some particular version of the your linux kernel. Without using seccomp performance will be significantly slowed down.

**Comment by fsquillace** [comment]
So, JuNest will go more into the direction of Linux namespaces. The latest release is making it as the default backend and proot as a secondary because Linux user namespace is now enabled by default in the majority of Linux distros. The slow deprecation of proot is due to the fact that maintenance of proot becomes more and more complex. The other problem is that JuNest requires proot to be statically compiled which is something that does not seems to be supported anymore. I will keep an eye from time to time to understand if things change in the proot world.

For now, I can just suggest you to move to Linux namespaces backend if you can. Closing.
