### ISSUE TITLE
Bind mounts are skipped using groot when junest is on a zfs set

### ISSUE THREAD

**Issue by tsjk** [fsquillace/junest#203]
Around lines 77-81 we have
```
    if ! chroot_maybe_add_mount "! is_mountpoint '$CHROOTDIR'" --bind "$CHROOTDIR" "$CHROOTDIR"
    then
        warn "Failed mount of directories. $CHROOTDIR is already a mountpoint. Skipping it..."
        return 0
    fi
```

Do you really want to return there? That makes all the binds that would follow to be skipped.
I have junest on a zfs set, making /proc/self/mounts having a line saying
```
zpool/DATA/.junest /home/user/.junest zfs rw,noatime,xattr,posixacl 0 0
```
However, I'm still interested in getting the rest of the binds. I've removed the "return 0", and think I've got a better result. Although I'm not sure if that self-bind should be applied here too.

**Comment by fsquillace** [comment]
This part of code is a read only operation which checks whether the specified path represents a mountpoint or not.

In case the mountpoint already exists there is no point to go further. Mounting an already existing mountpoint will result as an error.

**Comment by tsjk** [comment]
Yes, okay. The call
```
chroot_maybe_add_mount "! is_mountpoint '$CHROOTDIR'" --bind "$CHROOTDIR" "$CHROOTDIR"
```
makes sense, as the mount is only made if it isn't a mount point. However, if return is ordered when that bind isn't performed, the rest of the binds are not performed either. Meaning, no /dev, /sys, /home, nor whatever else. At least that was my observation, and surely that is not the aim.

Running with proot, which I managed after some extra work needed for seccomp, does not exhibit this same behaviour. There, there are no complaints with the same underlying structure.

**Comment by fsquillace** [comment]
That's because proot has its own way for binding directories and that code is not used at all as the backend is different. The code you mentioned will be executed only with either `groot` backend via `-g` option or linux namespaces via `-u` option.

About the mountpoint check, your observation is correct indeed. As stated in [line 4](https://github.com/fsquillace/junest/blob/master/bin/groot#L4) that part of `groot` has been wrote from another script which makes the check only on the root directory.

I guess the reason it is in this way might be that is preferable to fail fast in case preconditions are not satisfied rather to carry on wrongly configured mounting. The precondition is that when running `groot` the root directory should be free from having any mount to it. 

By adopting the solution of checking each single directory inside the root and skip those that are already mounted, the problem I can see is that it might be that the existing mountpoint can be wrongly mounted in different ways (i.e. by recursive, by different fstype, etc) which may alter the intended behavior. So, the simplest solution here is to skip everything and let the user assure to remove any mounting in root directory.

**Comment by tsjk** [comment]
Well, alright. I don't think I'd like to immerse myself in discussions. I'm just saying that if junest is a ZFS set, behaviour is different. I've now applied the following patch to my groot, just to make things clear:
```
diff --git a/bin/groot b/bin/groot
index cb4952f..a115cfb 100755
--- a/bin/groot
+++ b/bin/groot
@@ -74,9 +74,9 @@ function chroot_maybe_add_mount() {
 function chroot_setup() {
     $OPT_NO_UMOUNT || check_and_trap 'chroot_teardown' QUIT EXIT ABRT KILL TERM INT

-    if ! chroot_maybe_add_mount "! is_mountpoint '$CHROOTDIR'" --bind "$CHROOTDIR" "$CHROOTDIR"
+    if ! $MOUNT --bind "$CHROOTDIR" "$CHROOTDIR"
     then
-        warn "Failed mount of directories. $CHROOTDIR is already a mountpoint. Skipping it..."
+        warn "Failed mount of $CHROOTDIR - skipping mounts."
        return 0
     fi

```

And, I do not get the warning, nor any errors. Meaning that the mount did not fail and all is good.
I still need groot to use yaourt, it seems. :)
