### ISSUE TITLE
Are opengl programs supported?

### ISSUE THREAD

**Issue by KingDuckZ** [fsquillace/junest#209]
As per the title, are opengl programs supposed to work? I'm trying glewinfo and glxgears, they both fail with this message:

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Error: glewCreateContext failed

Ultimately, I'm trying to run openra.

**Comment by fsquillace** [comment]
It is possible but you need to make sure that junest has the right driver installed. For instance if the host OS is running X server with nvidia driver junest has to have the same driver installed. 

I created a junest environment with intel driver and `mesa` and `mesa-demos` installed and `glxgears` works like a charm if I run the X server in host OS with the intel driver. Using the exact same junest env I get the same error as yours if I run the X server with nvidia.

**Comment by KingDuckZ** [comment]
Thanks for the answer, although this is not useful for me anymore. Hopefully it will help others looking for the same thing in the future!

**Comment by ayaka14732** [comment]
Here is the way to use GPU (nvidia) with junest:

1. `git clone` [`nvidia-utils-beta`](https://aur.archlinux.org/packages/nvidia-utils-beta) and [`nvidia-beta-dkms`](https://aur.archlinux.org/packages/nvidia-beta-dkms) from AUR
1. Get the host nvidia version by `cat /proc/driver/nvidia/version`
1. `git log` in the two repositories to see the corresponding commits
1. `git checkout` in the two repositories to the corresponding commits
1. Build and install by `makepkg -si`

If `makepkg -si` does not work, you can install them manually:

```sh
$ sudo pacman -U nvidia-utils-beta/*.pkg.tar nvidia-beta-dkms/*.pkg.tar
loading packages...
resolving dependencies...
looking for conflicting packages...
:: nvidia-utils-beta and nvidia-utils are in conflict. Remove nvidia-utils? [y/N] y
:: opencl-nvidia-beta and opencl-nvidia are in conflict. Remove opencl-nvidia? [y/N] y                                                                        
:: nvidia-beta-dkms and nvidia are in conflict. Remove nvidia? [y/N] y
:: nvidia-beta-dkms and nvidia-dkms are in conflict. Remove nvidia-dkms? [y/N] y
...
```

Add the packages to `/etc/pacman.conf`, so that `pacman -Syu` will not update them:

```
IgnorePkg = nvidia nvidia-utils nvidia-dkms opencl-nvidia
```
