### ISSUE TITLE
Setting PATH

### ISSUE THREAD

**Issue by DiagonalArg** [fsquillace/junest#222]
[Installation instructions](https://github.com/fsquillace/junest) tell us (Method one) to:

`export PATH=$JUNEST_HOME/bin:$PATH`

while (Method two):

`export PATH=$JUNEST_HOME/opt/junest/bin:$PATH`

I'm not clear on which to do.  That first one is going to give `junest` binaries priority.  When I try that with Method two, junest errors out when I run it:

```
$ junest -f
bash: error while loading shared libraries: libreadline.so.8: cannot open shared object file: No such file or directory
```

**Comment by fsquillace** [comment]
I am not sure where you are looking at but method one and method two are very similar in term of setting PATH:

`export PATH=/opt/junest/bin:$PATH`

`export PATH=~/.junest/opt/junest/bin:$PATH`

The only difference is that method one takes the `junest` script from the git repository instead of the image content.

This should not produce the error you got but that is generally related to a missing library. Try to reinstall junest and upgrade to latest version.

**Comment by DiagonalArg** [comment]
It's under "Method one" and "Method two" in that link (in the OP).  Your Readme.md.  Note:

`.junest/bin`

**vs**

`.junest/opt/junest/bin`

I solved the problem by using both, and putting them *after* the system's PATH:

`export PATH="$PATH:$HOME/.junest/opt/junest/bin:$HOME/.junest/bin"`
