### ISSUE TITLE
[Question] Mount an iso using junest?

### ISSUE THREAD

**Issue by awsms** [fsquillace/junest#239]
I'm trying to mount an iso using `sudo mount -o loop` , but apparently this isn't working.
Is junest relying to the host fstab, or it has its own?

**Comment by fsquillace** [comment]
Inside JuNest is possible to access as a fakeroot (with UID set as 0). This allows certain applications (i.e. package manager) to believe that the user has root privileges so that actions can be performed anyway. Certain commands, like `mount`, performs system calls that requires to have a real root privileges. For such commands, JuNest alone cannot help. Specifically to the `mount` command you can use `fuser` which allows to mount in user namespace without root privileges.
