### ISSUE TITLE
AUR packages having `cp -a` throw `failed to preserve ownership`

### ISSUE THREAD

**Issue by DroidFreak32** [fsquillace/junest#305]
For example package `android-sdk-cmdline-tools-latest`:

```
cp: failed to preserve ownership for '/home/rushab/.cache/yay/android-sdk-cmdline-tools-latest/pkg/android-sdk-cmdline-tools-latest/opt/android-sdk/cmdline-tools/latest/lib/profgen': Invalid argument
cp: failed to preserve ownership for '/home/rushab/.cache/yay/android-sdk-cmdline-tools-latest/pkg/android-sdk-cmdline-tools-latest/opt/android-sdk/cmdline-tools/latest/lib': Invalid argument
cp: failed to preserve ownership for '/home/rushab/.cache/yay/android-sdk-cmdline-tools-latest/pkg/android-sdk-cmdline-tools-latest/opt/android-sdk/cmdline-tools/latest': Invalid argument
```
However replacing them with `cp -r` works totally fine

**Comment by onemoresuza** [comment]
It seams to be a problem with packages which, in some way, try to either change or preserve the ownership of a file.

The AUR package [heroic-games-laucher-bin](https://aur.archlinux.org/packages/heroic-games-launcher-bin) fails, for instance, with `tar` throwing the following error:

> tar: \<name-of-the-file\>: Cannot change ownership to uid 0, gid 0: Invalid argument

Which I believe is caused by `makepkg`, since downloading the [.pacman file for 2.5.2](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.5.2/heroic-2.5.2.pacman) and running the same tar command --- `tar -xJv` --- doesn't cause this issue.

**Comment by Donokami** [comment]
> Which I believe is caused by `makepkg`, since downloading the [.pacman file for 2.5.2](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.5.2/heroic-2.5.2.pacman) and running the same tar command --- `tar -xJv` --- doesn't cause this issue.

I've got the same issue. @onemoresuza if you have an idea on how to fix it, I would love to know it!

**Comment by Donokami** [comment]
> > tar: <name-of-the-file>: Cannot change ownership to uid 0, gid 0: Invalid argument
> 
> Which I believe is caused by `makepkg`, since downloading the [.pacman file for 2.5.2](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.5.2/heroic-2.5.2.pacman) and running the same tar command --- `tar -xJv` --- doesn't cause this issue.

I found a (dirty) way to mitigate this. You just have to pass `FAKEROOTDONTTRYCHOWN=true` to your Junest environment
If anybody has a better way of doing this, it would be appreciated!

**Comment by fsquillace** [comment]
Thanks! I am updating JuNest image to include the variable `FAKEROOTDONTTRYCHOWN` set to `true` by default. This will fix the problem permanently.
