### ISSUE TITLE
Needs a new name?

### ISSUE THREAD

**Issue by jpellman** [fsquillace/junest#63]
Hi-

First off, I just wanted to thank you for making this.  JuJu is a super useful tool for allowing users to install packages in a nice sandbox without messing up the rest of the system.  

This isn't a technical issue, but I noticed that the project name is basically identical to Canonical's cloud software management tool (which appears to be much older; 2011 vs 2014).  You might want to consider switching to another name since, beyond causing confusion, this prevents the two packages from both being installed on the same system (I can't think of a scenario where anyone would want to do this right now, but hey- who knows?).

Cheers,
John Pellman

**Comment by fsquillace** [comment]
Hi John,

Thanks for your remarkable opinion about this project.
I knew about the Canonical tool but I did not expect that my system could have so much popularity. The result of this project arrived far beyond my expectation and I am noticing it is getting more and more popular during the time.

The JuJu name is not just a casual name that came in my mind but it actually has a meaning for me.
Few years ago I usually met my nerd friends in a bar called "JuJu" exchanging thoughts, opinions and ideas with them mostly about the IT world and that is the reason why I wanted to use that name for this system. For the moment I would like to keep this name although I am thinking to use it in conjunction with another word. What about juju-os?

If you have any ideas about new names please list them here so I will think about them.

Thanks again,
Filippo

**Comment by jpellman** [comment]
Off the top of my head, I can only think of portmanteaus.  Maybe jujutsu?  Ninjuju?

**Comment by cedric-vincent** [comment]
On Fri, Feb 20, 2015 at 09:03:27AM -0800, John Pellman wrote:
>    Off the top of my head, I can only think of portmanteaus. Maybe
>    jujutsu? Ninjuju?

Maybe "JuJu Tsu Linux"; this keeps the original name (and its meaning
for the author) and this should be enough to avoid the naming
collision in search engines and people minds.

**Comment by nikolowry** [comment]
+1 

I'm going to start incorporating this into my dokku CI flow and every time I attempt to google for advice/tips/etc. I'm flooded w irrelevant information.

I've been an Arch user for a while now and have officially given up on using aptitude on cloud server.

**Comment by fsquillace** [comment]
Thanks Cedric for your opinion about the new name. Also JuJu Tsu Linux seems a nice name to me. Your opinion about the naming is more than valuable since without your contribution, I guess, JuJu would not be as awesome as it is now ;)

The idea of using JuJu for CI is really nice. For instance, I started using JuJu with Travis and it works perfectly so that you can install the packages you need with the wide official/AUR ArchLinux repositories.

Filippo

**Comment by oliwarner** [comment]
I'd advise taking this bug a little more seriously (or at least urgently). Canonical aren't just using the name, they have a registered trademark on "JUJU" and you've as much just admitted to wilfully impinging on it.

If nothing else, the sooner you fix it, the sooner your community can get used to the new name.

**Comment by RobertDeRose** [comment]
@oliwarner Agreed and seconded!

**Comment by fsquillace** [comment]
@oliwarner Thanks for the heads up. You are right. The sooner JuJu will be renamed the better it will be for the community.

The fact "I just admitted to wilfully impinging on it" is quite wrong indeed. I just wanted to keep the name for the certain period mainly because I did not get any nice name so far and I did not have time slot available to dedicate on this issue. Anyway, this will be the main task I will work for the next days. I will probably send a list of few names so that you could vote on your favorite one.

I am wondering what does it happen if the name that we are going to choose will be registered by some company later on? Would I need to change the project name again? :D

Thanks again.

**Comment by oliwarner** [comment]
@fsquillace IANAL *but* trademarks don't have to be registered to be defensible. When you see a ™, that's somebody who hasn't registered Ⓡ. Somebody can attempt to squat on an existing name but even if their application wasn't denied; they'd probably lose any fight with existing trademark users.

Of course, if you use a name that is currently in use and in a similar class (eg software), but is currently unregistered by its user and later on they register it, you *might* have problems if they can show they were using it first. Who knows. Law at this level is less to do with fairness and more to do with the amount of money you can afford to throw at convincing a jury you are right.

Best of luck in the future.

**Comment by fsquillace** [comment]
Guys,

Many names came into my mind in these days but no one convinced me really well since either they did not have any useful meaning or they were too long, therefore I could not provide a list of interesting names.

Just one name was attracting me for different reasons. So, I am pleased to announce that the new candidate name for this distro is "jujube".

The main advantage on using this name are:
- This will keep the original name;
- There are no trade marks about jujube within software related classes (I searched in https://www.ipo.gov.uk/tmtext.htm);
- Jujube is a small tree that produces some fruits that are as small as JuJu distro :D
- We can implicitly takes the jujube fruit as the symbol for this distro.

Let me know if there are relevant objections on this.

Regards,
Filippo

**Comment by aneeshusa** [comment]
+1 sounds good to me!

**Comment by fsquillace** [comment]
Hi,

Unfortunately, this issue it is far from being resolved.

According to Canonical, it looks that even JuJube (and at this point I guess any word containing *juju* such as juju tsu) cannot be taken because of the trademark which is really sad...

I will try to think to something else...
